### ISSUE TITLE
Neuinstallation funktioniert nicht mehr

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/zotkat#13]
Falls man jetzt versucht die Translators hier neu zu verwenden ohne vorher bereits die zu haben, dann kommt eine Fehlermeldung wegen den Metadaten und der Export-Translator kann nicht ausgewählt werden. Durch das Löschen der Zeilen

```
/* jshint ignore:start */
```

geht es wieder. Wie kann man JSHint hier benutzen, aber die ersten Zeilen (Metadaten in JSON) und letzten Zeilen (Tests) ignorieren?

**Comment by kba** [comment]
Man könnte Metadaten und Code in zwei Dateien aufsplitten und die über einen Grunt-Task zusammenfügen.

**Comment by zuphilip** [comment]
Die Translator werden am komfortablsten mit dem Addon https://github.com/zotero/scaffold erstellt. Damit kann man auch die Tests einfach laufen lassen, überprüfen oder updaten. Damit ist der normale Workflow, dass man eine Datei hochlädt. Idealerweise würde man diese vor der Prüfung in die verschiedenen Teile aufgeteilt werden. Kann das Grunt oder die bash?

**Comment by kba** [comment]
Im Moment ist Grunt nicht notwendig, da es keinen Build-Prozess gibt, bei dem JS/CSS komprimiert, CoffeeScript/Less übersetzt, Unit Tests ausgeführt werden sollen usw.

Wenn es nur darum geht, jshint auszuführen:

``` bash
sed '1,/^}/d' BIBFRAME.js|jshint -
```

Das löscht `d` alle Zeilen von der ersten Zeile `1` bis zur ersten mit einer schliessenden geschweiften Klammer beginnenden Zeile `/^}/` und führt jshint auf dem Rest der Datei aus.

**Comment by zuphilip** [comment]
Ja, genau, so etwas habe ich mir vorgestellt. Dies sieht alles gut aus. Vielen Dank, @kba ! :bow:
