### ISSUE TITLE
Zotero -> MARC21 export. Where do I insert Vol., issue, pages info ?

### ISSUE THREAD

**Issue by ztajoli** [UB-Mannheim/zotkat#22]
Hi to all,
sorry but I don't speack german.

My suggestion is to change line 370 of file MARC21XML.js

From
mapProperty(currentFieldNode, "subfield", {"code" : "h"} , descriptionArray.join(', ') );
to
mapProperty(currentFieldNode, "subfield", {"code" : "g"} , descriptionArray.join(', ') );

In MARC21 is better to insert volume, issue, pages of an article into 773 $g instead of 773 $h.
See the examples in official standard page:
https://www.loc.gov/marc/bibliographic/bd773.html

The best will be to create ALSO 773 $q but it is a complex task

**Comment by stweil** [comment]
Hi @ztajoli,

using English is fine. We'd also read issues in Italian, but might have difficulties answering in the same language then. :-)

Maybe we should update our README with English text to better support international users.

Regards
Stefan

**Comment by zuphilip** [comment]
Thank you for the report, see also https://github.com/zotero/translators/issues/762#issuecomment-215027924

I will try to look at it closely any time soon.

**Comment by zuphilip** [comment]
> In MARC21 is better to insert volume, issue, pages of an article into 773 $g instead of 773 $h.

Okay, it seems you are right. I will correct that.

> The best will be to create ALSO 773 $q but it is a complex task

I haven't seen the subfield $q in any entry of a catalogue here in Germany. Do you have any examples? Do you know if the 2009 LOC information are still up-to-date? Do you use MARC21 with RDA?

**Comment by ztajoli** [comment]
Hi,
773 $q is Enumeration and first page.
The official description is here with an example:
https://www.loc.gov/marc/bibliographic/bd76x78x.html
In fact is a section of SICI.
About SICI:  https://en.wikipedia.org/wiki/Serial_Item_and_Contribution_Identifier and
http://www.niso.org/apps/group_public/project/details.php?project_id=75

In fact 773 $q is a place where insert volume, issue, fasc,, start page data in  more standard way.

The site https://www.loc.gov/marc/bibliographic/ is the official home of MARC21 and it is up-to-date until April 2016, last update of MARC21.

I use MARC21 with AACR2

**Comment by zuphilip** [comment]
@ztajoli The MARC21 export translator here is updated and I changed the subfield to $g as you pointed out. Moreover, I added the SICI formatted description in subfield 773 $q. Maybe, we have to make this configurable, because I am still not sure, that we do use this subfield here as well.
