### ISSUE TITLE
Error-Meldung: Invalid or missing translator metadata JSON object in PicaSWB.js

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/zotkat#29]
Die Fehlermeldung wurde von @Duhem123 beim Testen vom PicaSWB translator in der Standalone Version festgestellt. Der Export funktioniert in dem Fall gar nicht.

**Comment by Duhem123** [comment]
@zuphilip  Besten Dank fürs Öffnen des Tickets. 

Der Debug-Log war ein guter Tipp. Dort finde ich folgende Fehlermeldung:

[JavaScript Error: "Invalid or missing translator metadata JSON object in PicaSWB.js" {file: "file:///C:/Users/[...]PicaSWB.js" line: 0}]

[JavaScript Error: "Invalid or missing translator metadata JSON object in PicaSWB.js" {file: "file:///C:/Users/[...]/PicaSWB.js" line: 0}]

version => 4.0.28.7, platform => Win32, oscpu => Windows NT 6.1, locale => en-US, appName => Zotero, appVersion => 4.0.28.7

**Comment by socheres** [comment]
@Duhem123 nach Kopieren und Exporteinstellung ist ein Neustart von Browser bzw. Standalone erforderlich. Vllt. klappt es dann.

**Comment by Duhem123** [comment]
Ich habe nach dem Kopieren der JS-Datei Zotero mehrfach neu gestartet (und zwischendurch auch den Rechner mal komplett runtergefahren). Die Exporteinstellung kann ich doch erst auswählen, sobald der Translator erkannt wurde. Insofern geht das aktuell nicht.

**Comment by zuphilip** [comment]
@Duhem123 Kannst Du einmal bei Dir die Datei PicaSWB.js überprüfen? Einfach in einem Texteditor öffnen. Darin darf kein HTML-Code sein, sondern müsste so aussehen: https://raw.githubusercontent.com/UB-Mannheim/zotkat/master/PicaSWB.js (Anonsten: Aktuelle Zotero Version ist 4.0.29.10 daher kann ein Update nicht schaden, obwohl ich nicht denke, dass dies hier relevant wäre.)

**Comment by Duhem123** [comment]
@zuphilip Jepp, genau das war es. Danke!

**Comment by Duhem123** [comment]
Close UB-Mannheim/zotkat/issues/29
