### ISSUE TITLE
bandzählung abhängig von zeitschriften

### ISSUE THREAD

**Issue by socheres** [UB-Mannheim/zotkat#30]
Die Bandzählung bei einigen Zeitschriften kommt zu der Bandzählung in WinIBW zusätzlich einige Buchstaben hinzu. Z.B. "$vN.S.8" Daher habe ich den Code wie folgt geändert, aber denke da gibt es elengantere Lösung?

``` javascript
if (item.volume && item.ISSN == "2031-5929") {
   volumeyearissuepage += "$vN.S." + item.volume; }
else if (item.volume) {
   volumeyearissuepage += "$v" + item.volume;
}
```

**Comment by zuphilip** [comment]
Was ist hier der Hintergrund für diese Regelung? Ist `N.S.` eine Abkürzung?

**Comment by socheres** [comment]
ja, es ist Abkürzung für eine neu begonnene Bandzählung innerhalb einer Zeitschrift. Wahrscheinlich Neue Serie oder so etwas. Es ist wohl Erfassungsregel nach RDA bzw. RAK
Einige Zss. haben diese Spezifika, daher wollte ich abhängig von der ISSN diese Zählung automaisch ersetzen, sonst muss man jedes Mal im Skript ändern.
![vol](https://cloud.githubusercontent.com/assets/1545743/17415211/1552f658-5a89-11e6-8717-326261f4f575.PNG)

**Comment by socheres** [comment]
das Objekt von "issnVolumeMapping" wird nicht erkannt. Das Exportergebnis sieht wie folgt aus:
4070 $v[object Object]28$j2015$h2$p91-106
