### ISSUE TITLE
Auf LIBREAS Aufsatz hinweisen

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/zotkat#36]
Evt. auch Video einbinden? https://github.com/libreas/ausgabe29/tree/master/05kim/video

**Comment by socheres** [comment]
du meinst in wiki?

**Comment by zuphilip** [comment]
Beispielsweise im Wiki und/oder auch schon einen Hinweis in der https://github.com/UB-Mannheim/zotkat/blob/master/README.md . Du kannst gerne auch etwas entwerfen/vorschlagen, wenn Du magst.

**Comment by socheres** [comment]
Habe in der https://github.com/UB-Mannheim/zotkat/blob/master/README.md sowie https://github.com/UB-Mannheim/zotkat/wiki/Bibliografie/5d52b0e2d69a5372240752e488c53dd38d5aa512 auf den Artikel hingewiesen. Ist es so O.K?

**Comment by zuphilip** [comment]
Jup.
