### ISSUE TITLE
keywords/tags exportieren

### ISSUE THREAD

**Issue by socheres** [UB-Mannheim/zotkat#38]
Keywords gibt es nicht als zotero-field. Wie kann man trotzdem `item.tags` exportieren?

``` js
        // keywords aus Fremddaten--> 5520
        if (item.tags) {
            writeLine("5520 |s|", item.tags);
        }
```

**Comment by zuphilip** [comment]
Wie soll dies genau aussehen in Pica? Die Tags in Zotero sehen beispielsweise so aus:

``` js
item.tags = [
    {"tag":"Structural Models","type":1},
    {"tag":"NEIO","type":1},
    {"tag":"Pricing","type":1},
    {"tag":"Sales Promotion","type":1},
    {"tag":"Sales Promotion Paradox","type":1}
];
```

**Comment by socheres** [comment]
Für nicht normierte keywords kann man das Feld 5520 in WiniBW nutzen. Und zwar vor dem ersten Keyword muss |s| stehen. Z.B.: 
5520 |s|Structural Models; NEIO; Pricing; Sales Promotion; Sales Promotion Paradox

**Comment by socheres** [comment]
@zuphilip bitte eine "kleine" Änderung noch. Mit jedem Tag muss das Feld 5520 wiederholt werden. Wenn wir das obige Bsp. nehmen, sähe das Exportergebnis wie folgt aus:
5520 |s|Structural Models
5520 |s|NEIO
5520 |s|Sales Promotion
5520 |s|Sales Promotion Paradox

**Comment by socheres** [comment]
ich habe mit folgendem Code getestet, aber das Ergebnis ist nicht ganz sauber `var i = 0, tagStatement;
        while (item.tags.length > 0) {
            tagStatement = item.tags.shift();
                var tagStatement = "|s|" + item.tags.map(function(tag) { return tag.tag; }).join('; ');
                writeLine("5520", tagStatement);
        }`

**Comment by socheres** [comment]
mit `var tagStatement = "|s|" + item.tags.map(function(tag) { return tag.tag; }).join('; ').split(";", 1);`kommt das Ergebnis sauber. Kann ich das so ändern?

**Comment by zuphilip** [comment]
Okay, dies ändert natürlich die Sachlage.

Ich würde so etwas vorschlagen:

``` js
for (var i=0; i<item.tags.length; i++) {
    writeLine("5520", "|s|" + item.tags[i].tag);
}
```

**Comment by socheres** [comment]
ja, mit deinem Vorschlag `for (var i=0; i<item.tags.length; i++) {
                var tagStatement = "|s|" + item.tags.map(function(tag) { return tag.tag; }).join('; ').split(";", 1);
                    writeLine("5520", "|s|" + item.tags[i].tag);    
        }` sieht gut aus. Bei meinem Vorschlag wurde das erste Tag/Keyword nicht exportiert.

**Comment by socheres** [comment]
außerdem noch eine kleine Änderung `writeLine("5520", "|s|" + item.tags[i].tag.replace(/ --/g, ';')); 
        }` Trennzeichen fürs präkombinierte Schlagwort ist ";", damit das Wort nach ";" beim Marc-Export in Unterfeld "$x"geschrieben werden. Z.B.:
5520 |s|Nature; Religious aspects; Christianity
650 0$aNature$xReligious aspects$xChristianity

**Comment by zuphilip** [comment]
Closed by #41
