### ISSUE TITLE
How to install the Wikidata QuickStatements translator?

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/zotkat#46]
(This question came over Twitter.)

**Comment by zuphilip** [comment]
Let me try to explain this here, before updating the documentation and think about how to handle the two languages:

1. Install [Zotero](https://www.zotero.org/)
2. Go to the [Zotero `Data Directory`](https://www.zotero.org/support/zotero_data) (usually in your Firefox profile) and then to the subfolder `translators`
3. Copy the raw (!) text file of the [Wikidata QuickStatements translator](https://raw.githubusercontent.com/UB-Mannheim/zotkat/master/Wikidata%20QuickStatements.js) there
4. Restart Zotero and/or Firefox
5. Go to `Preferences...` > `Export` > `Default Output Options` and choose `Wikidata QuickStatements` there (if this list is empty or the option does not occur there then close the preferences dialog and open it again)

Then you can either use drag and drop or the shortcuts for the QuickCopy.

**Comment by pigsonthewing** [comment]
Note that users can select to set preferences on a per-domain basis.

For example, to use 'Wikidata QuickStatements' when on tools.wmflabs.org, but use 'Wikipedia Citation Templates' when on wikipedia.org
