### ISSUE TITLE
Adding monolingual title fails

### ISSUE THREAD

**Issue by pigsonthewing** [UB-Mannheim/zotkat#47]
The script fails adding P1476 because the language is mandatory.  Instead of:

`LAST	P1476	"Twenty Five Albums that Rocked the World"`

please use:

`LAST	P1476	en:"Twenty Five Albums that Rocked the World"`

Replacing "en" with the appropriate ISO code if necessary. Country-specific codes can be used, e.g.:

`LAST	P1476	en-gb:"Twenty Five Albums that Rocked the World"`

**Comment by zuphilip** [comment]
Okay, I see. Is lower case and uppercase in these language code important? In Zotero most of the times we save them as `en-GB` for example.

**Comment by zuphilip** [comment]
Okay, I see. Is lower case and uppercase in these language code important? In Zotero most of the times we save them as `en-GB` for example.

**Comment by pigsonthewing** [comment]
It seems to require all-lowercase.
