### ISSUE TITLE
[WQS] Expand typeMapping

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/zotkat#51]
At the moment we just have the Q-numbers for journalArticle and book, but the other types are missing. It would nice to add some of the missing ones. Zotero has the following itemTypes (types already handled are stroke through):
* artwork
* attachment
* audioRecording
* bill
* blogPost
* ~~book~~
* bookSection
* case
* computerProgram
* conferencePaper
* dictionaryEntry
* document
* email
* encyclopediaArticle
* film
* forumPost
* hearing
* instantMessage
* interview
* ~~journalArticle~~
* letter
* magazineArticle
* manuscript
* map
* newspaperArticle
* note
* patent
* podcast
* presentation
* radioBroadcast
* report
* statute
* thesis
* tvBroadcast
* videoRecording
* webpage

and implicitely (through a hack in extra) also the following additional CSL types could be supported:
* dataset
* entry
* figure
* musical_score
* pamphlet
* review
* review-book
* treaty

**Comment by pigsonthewing** [comment]
artwork = Q838948
attachment = Q17709279 ?
audioRecording = Q30070318
bill = Q30070318 (in the context of invoice)
blogPost = Q17928402
bookSection = Q1980247
case = Q2334719 (legal case)
computerProgram = Q40056
conferencePaper = Q23927052
dictionaryEntry = Q30070414
document = Q49848
email = Q30070439
encyclopediaArticle = Q17329259
film = Q11424
forumPost = Q7216866
hearing = Q30070550
instantMessage = Q30070565
interview = Q178651
letter = Q133492
magazineArticle = Q30070590
manuscript = Q87167
map = Q4006
newspaperArticle = Q5707594
note = Q489850 (in the context of a footnote) or Q1619873 (in the context of a briefing note)
patent = Q253623
podcast = Q24634210
presentation = Q604733
radioBroadcast = Q1555508
report = Q10870555
statute = Q820655
thesis = Q1266946
tvBroadcast = Q15416
videoRecording = Q30070675
webpage = Q36774

**Comment by pigsonthewing** [comment]
Also:

dataset = Q1172284
entry = [please give context]
figure = Q30070753 (in the context of image)
musical_score = Q187947
pamphlet = Q190399
review = Q265158 ?
review-book = [please define - does this mean a review of a book, Q637866 ?]
treaty = Q131569

**Comment by zuphilip** [comment]
> bill = Q30070318 (in the context of invoice)

`bill` is here meant in the legal sense; thus I guess Q686822 should be fine.

**Comment by zuphilip** [comment]
> review = Q265158 ?
> review-book = [please define - does this mean a review of a book, Q637866 ?]

Yes, that looks fine.

> attachment = Q17709279 ?
> entry = [please give context]

I doubt that `attachment` and `entry` are anyhow useful. Therefore, I suggest in these two cases to not add a P31 statement at all.

**Comment by zuphilip** [comment]
Also `note` I would skip, or at least not map to anything...

**Comment by zuphilip** [comment]
@pigsonthewing Thank you very much for the mapping! 🎉 🎆 

I copied it into the WQS translator in the current pull request #50.
