### ISSUE TITLE
WQS: add series ordinal on author string

### ISSUE THREAD

**Issue by nichtich** [UB-Mannheim/zotkat#52]
The qualifier "series ordinal" (P1545) should to be added for each author.

**Comment by zuphilip** [comment]
It should be easy to add an increasing number for this property which would then reflect the ordering in Zotero. My main question here is: can/should we assume that the ordering of authors in Zotero is correct? This information comes usually from the scraped information from the publisher's website or some BibTeX file etc. On one hand all information in this process can have some errors, but on the other hand a statement with such series ordinal looks more trustful. CC @pigsonthewing

**Comment by pigsonthewing** [comment]
> can/should we assume that the ordering of authors in Zotero is correct? 

I think a better question is: "Does Zotero preserve the ordering from the source?" From a _brief_ test, using COinS for the input,  it appears that, it does. Here is my test data, and the resultant wiki-code:

https://en.wikipedia.org/wiki/User:Pigsonthewing/Zotero-test

(There is, though, a possible bug with Wikipedia's COinS markup, as described there.)

**Comment by zuphilip** [comment]
@pigsonthewing Thank you for testing.

> "Does Zotero preserve the ordering from the source?"

Yes, that should be true.

I guess this means we should try to add these serial ordinal.

I am not sure when I find the time to look into this...

**Comment by zuphilip** [comment]
Closed by 1f81d6c.
