### ISSUE TITLE
Include a description

### ISSUE THREAD

**Issue by pigsonthewing** [UB-Mannheim/zotkat#57]
When outputting a citation in Wikidata QuickStatements format, a description could be included, dependent on the item type.

For example:

`LAST [tab] Den [tab] "journal article"`

or

`LAST [tab] Den [tab] "book"`

It may be possible to build more useful descriptions, by adding, say, a journal name, or a date.

`LAST [tab] Den [tab] "journal article from 'Proceedings of the Royal Society B'"`

or

`LAST [tab] Den [tab] "book published in 2010"`

**Comment by zuphilip** [comment]
Closed by 09cb28c.
