### ISSUE TITLE
nichtsortierzeichen "@" im Titelanfang

### ISSUE THREAD

**Issue by socheres** [UB-Mannheim/zotkat#6]
im "titleStatement" noch folgende Bedingung erforderlich:
nach einem im Anhang aufgelisteten Artikel im Titelanfang soll ein Nichtsortierzeichen "@" automatisch hinzugefügt werden. 
[ARTIKEL.pdf](https://github.com/UB-Mannheim/zotkat/files/137992/ARTIKEL.pdf)

hier zwei Beispiel:
4000 L' @archeologia punica e gli dèi degli altri

4000 The @frontal lobes revisited

**Comment by socheres** [comment]
@zuphilip habe schon angpasst

**Comment by zuphilip** [comment]
@socheres Okay, ich sehe den PR #8 dazu. Werde sobald wie möglich mir dies genauer ansehen...

**Comment by socheres** [comment]
@zuphilip ist nicht so elegant gelöst, aber tut was es soll:)
