### ISSUE TITLE
Add license info (ReadMe and/or Wiki)

### ISSUE THREAD

**Issue by michaelavoigt** [UB-Mannheim/zotkat#61]
License info is available on file level – which is good of course. You could add license file for the entire repository (cf. https://help.github.com/articles/adding-a-license-to-a-repository/). 
This might be tricky if content is licensed under different terms. Alternatively, you could include (human readable ) license details in the ReadMe – e.g.
- Translator available under AGPL license (check individual files for detailed information 
- Bash scripts available under ...
- Wiki texts available under ... 

It could also be helpful to include (human readable) license details in the Wiki home page (in case others want to re-use wiki texts only)

**Comment by zuphilip** [comment]
Ich habe mal im Wiki einen Footer hinzugefügt, z.B. https://github.com/UB-Mannheim/zotkat/wiki/Fehler-melden . @michaelavoigt Was hältst Du davon?

Das [Bash Script](https://github.com/UB-Mannheim/zotkat/blob/master/jshint.sh) würde ich dann auch als CC0 ausgeben; @kba bist Du einverstanden?

**Comment by kba** [comment]
Sure, CC0 fine by me.

**Comment by zuphilip** [comment]
Closing as we add a license file, new section in the README for full details, individual license info per file. Thank you @michaelavoigt for the report!
