### ISSUE TITLE
K10plus

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/zotkat#84]
Bald kommt der K10plus und damit werden individuelle Translators für das Picaformat im SWB und GBV hinfällig. Wir bräuchten dann also einen K10plus-Pica-Translator aus der Vereinigung von den den beiden bestehenden, welcher sich nach dem Handbuch http://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=index&kattype=Standard&val=-1&adm=0 richtet.

**Comment by socheres** [comment]
bis März 2019 werden wir bei uns in IxTheo auch die Feldänderungen, die sich aus k10plus ergibt, nachziehen. Wir können kollaborativ ein PicaK10 Export-Translator schreiben, dass am Besten alle unselbständigen Dokumenttypen abdecken (Aufsätze, Rezension, Beiträge und Buchkapitel).

**Comment by hemmefelix** [comment]
Eine Kollegin aus unserer Katalogisierung und ich würden gerne helfen und daran mitarbeiten.

**Comment by socheres** [comment]
@zuphilip Legst du unter https://github.com/UB-Mannheim/zotkat eine neue Datei "PicaK10plus" an? In der neuen Datei sollten wir die Mappings dann auslagern, z.B. hier bei uns: https://github.com/ubtue/zotkat/blob/master/PicaSWB.js

**Comment by socheres** [comment]
z.I. Katalogisierungshandbuch für unselbstädige Werke: https://opus.k10plus.de/frontdoor/deliver/index/docId/415/file/K10plus_Unselbststaendige_Werke.pdf

**Comment by socheres** [comment]
hier Tübinger Anpassung mit Kommentar im Code (noch vorläufig): https://github.com/socheres/zotkat/blob/master/PicaSWB.js

**Comment by socheres** [comment]
@zuphilip der Code #87 meldet Fehler beim Exportieren. Habe auch keinen Fehler entdecken können. Kannst du bitte nochmal nachschauen? Habe noch paar Code ergänzt https://github.com/socheres/zotkat/blob/k10plus/K10plus.js

**Comment by zuphilip** [comment]
@socheres Sorry für die späte Antwort. Ich glaube es gab ein Problem, wenn es keine ISSN vorhanden war. Sollte jetzt gefixt sein und ich habe den PR auch endlich mal angenommen.
