### ISSUE TITLE
Wikidata translator wird nicht erkannt

### ISSUE THREAD

**Issue by jneubert** [UB-Mannheim/zotkat#85]
Nach dem Speichern von https://raw.githubusercontent.com/UB-Mannheim/zotkat/master/Wikidata%20QuickStatements.js im `translators` Verzeichnis wird das neue Format unter der Auswahl "Standardformat" (Einstellungen Export) nicht angeboten. 

Neustarten von Zotero (5.0.58) und "Jetzt aktualisieren" (Einstellungen Erweitert) hat keinen Einfluss. Dass das Zotero-Datenverzeichnis korrekt ist, habe ich überprüft. Zuvor habe ich zotkat auf diesem Rechner nicht benutzt.

**Comment by zuphilip** [comment]
Ein Neustart von Zotero müsste normalerweise genügen um den neuen Translator zu laden. Kannst Du nach einem Neustart von Zotero einmal auf `Hilfe` und dann `Fehler melden...` klicken und den Fehlerbericht (ohne sensitiven Daten) hierhin kopieren? Kannst Du nochmals kontrollieren in Deinem `translators`-Verzeichnis, dass die Datei `Wikidata QuickStatements.js` vorhanden ist? (Sonst kann ich mir dies nächste auch direkt ansehen auf der SWIB18.)

**Comment by jneubert** [comment]
Danke für's Reinschauen. Die Datei ist da. Das Fehlerfenster zeigt:

> Es wurden keine Fehler registriert, seitdem Zotero gestartet ist.
>
> version => 5.0.58, platform => Win32, oscpu => Windows NT 6.1; WOW64, locale => de, appName => Zotero, appVersion => 5.0.58, extensions => Zotero LibreOffice Integration (5.0.14.SA.5.0.58, extension), Zotero Word for Windows Integration (5.0.9.SA.5.0.58, extension), Shockwave Flash (27.0.0.170, plugin)

Was ich auch noch versucht habe, ist ein "touch" auf das Verzeichnis und die Datei - ebenfalls ohne Erfolg. 

Was mich dabei auch irritiert: Im translators-Verzeichnis sind 540 .js-Dateien. Es werden in Zotero aber nur 14 zur Auswahl angeboten.

Wär' klasse, wenn wir während der SWIB eine Gelegenheit fänden, kurz drauf zu schauen.

**Comment by zuphilip** [comment]
Kannst Du das Format für das Exportieren eines einzelnen Eintrages auswählen also aus dem Kontextmenü (Rechtsklick) und dann `Ausgewählten Eintrag exportieren...`?`

> Was mich dabei auch irritiert: Im translators-Verzeichnis sind 540 .js-Dateien. Es werden in Zotero aber nur 14 zur Auswahl angeboten.

Das ist normal, da die meisten Translator für das Web Scraping sind und nur wenige zum Importieren und exportieren. Du kannst die Import-Translators auflisten mit:
```sh
grep -E '"translatorType": (2|3|6|7|10|11|14|15)' *.js
```
Und klar, wir können dies auch auf der SWIB weiter ansehen...

**Comment by jneubert** [comment]
Die Typ-Aufzählung war der entscheidende Hinweis: Die "Wikidata QuickStatements.js" hatte bei mir auf der Platte den Typ 4. Das habe ich natürlich nicht bewusst geändert. Allerdings hatte es nach dem Verschieben der Datei eine Seltsamkeit gegeben: Sie war (wenn ich mich richtig erinnere) in Wikidata.js umbenannt worden. Ich habe sie dann händisch zurückbenannt. Möglicherweise war bei diesen Aktionen von Zotero der Typ "angepasst" worden. Wie auch immer: Nach Löschen und erneutem Runterladen wird der Translator erkannt, ist verwendbar und funktioniert. Vielen Dank für die Hilfe, und bis übermorgen - Joachim
