### ISSUE TITLE
Project Muse - Materialart wird bei Aufsätzen nicht erkannt

### ISSUE THREAD

**Issue by benkdrager** [UB-Mannheim/zotkat#92]
Auf der Plattform Project Muse werden bei frei verfügbaren Aufsätzen bzw. bei Aufsätzen auf die ich Volltext-Zugriff über meine Institution habe die Materialart nicht erkannt. Diese Aufsätze werden stets als Website mit fehlenden Metadaten wie Autor, Seitenzahl etc. von Zotero ausgelesen. In diesen Fällen fehlen jeweils im Seitenquelltext der Website die "mata-tags", welche üblicherweise die genannten Metadaten enthalten. 
Ich habe bereits die Zotero Foren und das Web durchforscht, jedoch keinen Hinweis auf dieses Problem finden können. Den entsprechenden translator habe ich bereits ersetzt und das Verfahren auch aus verschiedenen Netzwerken getestet.
Gibt es in dieser Runde eventuell ähnliche Erfahrungen oder Hinweise?

**Comment by socheres** [comment]
Ja, wir hatten auch Probleme mit Project-Muse-Webseite: https://github.com/ubtue/DatenProbleme/issues/1132#issuecomment-702703555Hier der Hier der modifizierte Translator für Zeitschriften, die wir indexieren. Bei anderen Zeitschriften könnten Fehler auftreten, daher "mit Vorsicht" zu genießen. https://github.com/socheres/Zoterobearbeitung/blob/master/zotero_master/translators/Project%20MUSE.js
Außerdem sehe ich in Ihrer Anleitung zum Batch-Skript, dass das WinIBW nach Speichern der Metadaten neu zu starten ist. Man kann auch ohne Neustart des WinIBW-Programms mit der Tastaturkombi "Strg+alt+shift+R" die WiniBW-Skripte neu laden.

**Comment by benkdrager** [comment]
Vielen Dank für den Hinweis und den modifizierten Translator. Ich werde das mal ausprobieren. Danke!

**Comment by socheres** [comment]
Project MUSE.js wurde überarbeitet und in die Master integriert:https://github.com/zotero/translators/pull/2307
Issue kann geschlossen werden.
